#!/bin/bash
V_SCRIPT_FOLDER=$(cd "$(dirname "$0")"; pwd)
if [ $# -lt 3 ];
then
	echo "usage: $0 <type:object|set> <def_folder> <router_folder>"
	exit 1;
fi

V_TYPE=$1
V_DEF_FOLDER=$2
V_ROUTER_FOLDER=$3

if [ ! -d ${V_DEF_FOLDER} ]; then
	echo "Def folder's not existed, Exiting";
	exit 0;
fi

if [ ! -d ${V_ROUTER_FOLDER} ]; then
	echo "Router folder's not existed, Exiting";
	exit 0;
fi

> /tmp/sql.sql
if [ "${V_TYPE}" == "object" ] || [ "${V_TYPE}" == "OBJECT" ];then
	for xml in `find ${V_DEF_FOLDER} -name "*.xml"`
	do
		V_MOD="${xml/${V_DEF_FOLDER}/}"
		V_MOD=$(echo ${V_MOD} | sed 's/^\///' | sed -r 's/\.[^\.]+//g')

		V_MOD_NAME=$(basename "${V_MOD}")
		V_MOD_PATH=$(dirname "${V_MOD}")
		if [ "${V_MOD_PATH}" == "." ]; then
			V_MOD_PATH=""
		fi

		V_STANDARD_MOD=$(echo "${V_MOD_PATH}" | sed 's/\//\./g')
		V_STANDARD_MOD=${V_STANDARD_MOD}.${V_MOD_NAME}
		V_STANDARD_MOD=$(echo ${V_STANDARD_MOD} | sed 's/^\.//')

		php ${V_SCRIPT_FOLDER}/object_builder.php ${V_STANDARD_MOD} ${V_DEF_FOLDER} ${V_ROUTER_FOLDER} ${V_SCRIPT_FOLDER}/php/mysql/create_mysql_schema_for_objects.tpl >> /tmp/sql.sql
	done
else
	for xml in `find ${V_DEF_FOLDER} -name "*.xml"`
	do
		V_MOD="${xml/${V_DEF_FOLDER}/}"
		V_MOD=$(echo ${V_MOD} | sed 's/^\///' | sed -r 's/\.[^\.]+//g')

		V_MOD_NAME=$(basename "${V_MOD}")
		V_MOD_PATH=$(dirname "${V_MOD}")
		if [ "${V_MOD_PATH}" == "." ]; then
			V_MOD_PATH=""
		fi

		V_STANDARD_MOD=$(echo "${V_MOD_PATH}" | sed 's/\//\./g')
		V_STANDARD_MOD=${V_STANDARD_MOD}.${V_MOD_NAME}
		V_STANDARD_MOD=$(echo ${V_STANDARD_MOD} | sed 's/^\.//')

		php ${V_SCRIPT_FOLDER}/set_builder.php ${V_STANDARD_MOD} ${V_DEF_FOLDER} ${V_ROUTER_FOLDER} ${V_SCRIPT_FOLDER}/php/mysql/create_mysql_schema_for_sets.tpl >> /tmp/sql.sql
	done
fi
cat /tmp/sql.sql | sort | uniq
rm -f /tmp/sql.sql
