#!/bin/bash
if [ $# -lt 3 ];
then
	echo "usage: $0 <src_dir> <target_dir> <type:object|set|queue|index>"
	exit 1;
fi

V_SCRIPT_FOLDER=$(cd "$(dirname "$0")"; pwd)
V_SOURCE=$1
V_TARGET=$2
TYPE=$3

cd ${V_SCRIPT_FOLDER}
./build_${TYPE}_mysql_schemas.sh ${V_SOURCE} ${V_TARGET}
